export { createApp } from './createApp'
export { h } from './h'
export { renderSlots } from './helpers/renderSlots'
export { provide, inject } from './helpers/apiInject'
export { createTextVNode } from './vnode'
export { getCurrentInstance } from './component'
